name: ROSMonitoring
root: ./
startup_window: server
pre_window: source ~/mrs_workspace/devel/setup.bash;
windows:
  - server:
      layout: tiled
      panes:
        - ./oracle.py --online --property property1 --port 8080 --discrete
        - ./oracle.py --online --property property2 --port 8081 --discrete
        - ./oracle.py --online --property property3 --port 8082 --discrete
        - ./oracle.py --online --property property4 --port 8083 --discrete
        - ./oracle.py --online --property property5 --port 8084 --discrete
        - ./oracle.py --online --property property6 --port 8085 --discrete
  - monitors:
      layout: tiled
      panes:
        - sleep 2;
          source ~/mrs_workspace/devel/setup.bash;
          roslaunch ~/mrs_workspace/src/monitor/run.launch
  - detectRed:
      layout: tiled
      panes:
        - sleep 5;
          source ~/mrs_workspace/devel/setup.bash;
          roslaunch ~/mrs_workspace/src/sarc_environment/launch/detectred_instrumented.launch
