name: ROSMonitoring
root: ./
startup_window: server
pre_window: source ~/mrs_workspace/devel/setup.bash;
windows:
  - server:
      layout: tiled
      panes:
        - sh online_monitor.sh ../rml/uav1.pl 8080
        - sh online_monitor.sh ../rml/uav2.pl 8081
        - sh online_monitor.sh ../rml/uav3.pl 8082
        - sh online_monitor.sh ../rml/uav4.pl 8083
        - sh online_monitor.sh ../rml/uav5.pl 8084
        - sh online_monitor.sh ../rml/uav6.pl 8085
  - monitors:
      layout: tiled
      panes:
        - sleep 10;
          source ~/mrs_workspace/devel/setup.bash;
          roslaunch ~/mrs_workspace/src/monitor/run.launch
  - detectRed:
      layout: tiled
      panes:
        - sleep 20;
          source ~/mrs_workspace/devel/setup.bash;
          roslaunch ~/mrs_workspace/src/sarc_environment/launch/detectred_instrumented.launch
