nodes: # here we list the nodes we are going to monitor
  - node:
      name: pi
      package: detectred
      path: /home/ctc_das/mrs_workspace/src/sarc_environment/launch/detectred.launch
monitors: # here we list the monitors we are going to generate
  - monitor:
      id: monitor_1
      log: /home/ctc_das/mrs_workspace/src/log1.txt # file where the monitor will log the observed events
      silent: True # we let the monitor to print info during its execution
      warning: 1
      oracle: # the oracle running and ready to check the specification (localhost in this case)
        port: 8080 # the port where it is listening
        url: 127.0.0.1 # the url where it is listening
        action: nothing # the oracle will not change the message
      topics: # the list of topics this monitor is going to intercept
        - name: detect_fire_uav1 # name of the topic
          type: std_msgs.msg.Int8 # type of the topic
          action: log
          subscribers:
           - pi
  - monitor:
      id: monitor_2
      log: /home/ctc_das/mrs_workspace/src/log2.txt # file where the monitor will log the observed events
      silent: True # we let the monitor to print info during its execution
      warning: 1
      oracle: # the oracle running and ready to check the specification (localhost in this case)
        port: 8081 # the port where it is listening
        url: 127.0.0.1 # the url where it is listening
        action: nothing # the oracle will not change the message
      topics:
        - name: detect_fire_uav2 # name of the topic
          type: std_msgs.msg.Int8 # type of the topic
          action: log
          subscribers:
           - pi
  - monitor:
      id: monitor_3
      log: /home/ctc_das/mrs_workspace/src/log3.txt # file where the monitor will log the observed events
      silent: True # we let the monitor to print info during its execution
      warning: 1
      oracle: # the oracle running and ready to check the specification (localhost in this case)
        port: 8082 # the port where it is listening
        url: 127.0.0.1 # the url where it is listening
        action: nothing # the oracle will not change the message
      topics:
        - name: detect_fire_uav3 # name of the topic
          type: std_msgs.msg.Int8 # type of the topic
          action: log
          subscribers:
           - pi
  - monitor:
      id: monitor_4
      log: /home/ctc_das/mrs_workspace/src/log4.txt # file where the monitor will log the observed events
      silent: True # we let the monitor to print info during its execution
      warning: 1
      oracle: # the oracle running and ready to check the specification (localhost in this case)
        port: 8083 # the port where it is listening
        url: 127.0.0.1 # the url where it is listening
        action: nothing # the oracle will not change the message
      topics:
        - name: detect_fire_uav4 # name of the topic
          type: std_msgs.msg.Int8 # type of the topic
          action: log
          subscribers:
           - pi
  - monitor:
      id: monitor_5
      log: /home/ctc_das/mrs_workspace/src/log5.txt # file where the monitor will log the observed events
      silent: True # we let the monitor to print info during its execution
      warning: 1
      oracle: # the oracle running and ready to check the specification (localhost in this case)
        port: 8084 # the port where it is listening
        url: 127.0.0.1 # the url where it is listening
        action: nothing # the oracle will not change the message
      topics:
        - name: detect_fire_uav5 # name of the topic
          type: std_msgs.msg.Int8 # type of the topic
          action: log
          subscribers:
           - pi
  - monitor:
      id: monitor_6
      log: /home/ctc_das/mrs_workspace/src/log6.txt # file where the monitor will log the observed events
      silent: True # we let the monitor to print info during its execution
      warning: 1
      oracle: # the oracle running and ready to check the specification (localhost in this case)
        port: 8085 # the port where it is listening
        url: 127.0.0.1 # the url where it is listening
        action: nothing # the oracle will not change the message
      topics:
        - name: detect_fire_uav6 # name of the topic
          type: std_msgs.msg.Int8 # type of the topic
          action: log
          subscribers:
           - pi
     
